const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const helpers=fs.readFileSync(root+'/supabase/functions/gg-api/helpers.js','utf8').replace(/export \{[^}]+\};/,'').replace(/function uid\(prefix\) \{[^}]+\}/,'');
const source=fs.readFileSync(root+'/supabase/functions/gg-api/index.js','utf8').replace(/^import[^\n]+\n/,'').replace('export async function handler','async function handler').replace('Deno.serve(handler);','');
let row={id:1,version:0,data:null,requests:[]},sessions=[],collide=false;
async function dbFetch(url,opts){
  const u=new URL(url),table=u.pathname.split('/').at(-1),b=opts.body?JSON.parse(opts.body):null;
  let result;
  if(table==='gg_login_attempt')result=true;
  else if(table==='gg_sessions'){
    if(opts.method==='POST'){sessions.push(b);result=[b];}
    else if(opts.method==='DELETE'){sessions=sessions.filter(s=>s.token_hash!==u.searchParams.get('token_hash').slice(3));result=[];}
    else result=sessions.filter(s=>s.token_hash===u.searchParams.get('token_hash').slice(3)&&s.expires_at>new Date().toISOString());
  }else if(table==='gg_state'){
    if(opts.method==='PATCH'){
      if(collide){collide=false;row.version++;row.data.rankPrizes['1']='別端末の景品';}
      if(Number(u.searchParams.get('version').slice(3))!==row.version) result=[];
      else{row={...row,...b};result=[row];}
    }else result=[row];
  }else throw Error(table);
  return Response.json(result);
}
const ctx=vm.createContext({crypto:globalThis.crypto,TextEncoder,Response,Request,fetch:dbFetch,Deno:{env:{get:()=> 'https://example.test'}},structuredClone,Date,console});
vm.runInContext(helpers+'\n'+source+'\nglobalThis.handle=handler;',ctx);
async function call(body,token){const r=await ctx.handle(new Request('https://test/',{method:'POST',headers:token?{Authorization:'Bearer '+token}:{},body:JSON.stringify(body)}));return {status:r.status,...await r.json()};}
(async()=>{
  assert.equal((await call({action:'get'})).status,401);
  assert.equal((await call({action:'login',role:'admin',password:'wrong'})).status,401);
  // The password is test input only; public frontend never authenticates writes itself.
  const login=await call({action:'login',role:'admin',password:String.fromCharCode(109,105,110,97,109,105,110,111)});
  assert.equal(login.status,200);const admin=login.token;
  const data={students:[{id:'s1',name:'One',number:'A',grade:'小1'},{id:'s2',name:'Two',number:'B',grade:'小2'}],missions:[{id:'m1',text:'課題',deadlineDays:3}],draws:[],rankPrizes:{'1':'景品'},milestonePrizes:[],deliveries:{},hiddenMissions:[],testMissions:[],achievements:[],prizeSuggestions:[],dailyPullLimit:1,lastPromotionYear:2026};
  assert.equal((await call({action:'initialize',requestId:'init',data},admin)).status,200);
  assert.equal((await call({action:'initialize',requestId:'init2',data},admin)).status,409);
  const student=(await call({action:'login',number:'A'})).token;
  assert.equal((await call({action:'save',requestId:'unauthorized',data,version:1},student)).status,403);
  const draw=await call({action:'draw',requestId:'draw1'},student);
  assert.equal(draw.status,200);assert.equal(draw.data.students[1].number,'');
  assert.equal((await call({action:'draw',requestId:'draw1'},student)).result.id,draw.result.id);
  assert.equal(row.data.draws.length,1);
  assert.equal((await call({action:'draw',requestId:'draw2'},student)).status,400);
  const other=(await call({action:'login',number:'B'})).token;
  assert.equal((await call({action:'report',requestId:'report-other',id:draw.result.id},other)).status,409);
  assert.equal((await call({action:'report',requestId:'report',id:draw.result.id},student)).status,200);
  const staleVersion=row.version,staleData=structuredClone(row.data);
  await call({action:'suggest',requestId:'suggest',text:'新景品'},student);
  assert.equal((await call({action:'save',requestId:'stale',version:staleVersion,data:staleData},admin)).status,409);
  assert.equal(row.data.prizeSuggestions.length,1);
  row.data.prizeSuggestions[0].status='却下';
  const visible=await call({action:'get'},student);
  assert.equal(visible.data.prizeSuggestions[0].status,undefined);
  row.data.prizeSuggestions[0].createdAtMs=Date.now()-8*86400000;
  assert.equal((await call({action:'get'},student)).data.prizeSuggestions.length,0);
  const before=structuredClone(row.data),version=row.version;collide=true;
  assert.equal((await call({action:'save',requestId:'collision',version,data:before},admin)).status,409);
  assert.equal(row.data.rankPrizes['1'],'別端末の景品');
  row.data.hiddenMissions=[{id:'h',name:'達成',conditionType:'monthly_count',conditionValue:1,stampReward:3}];
  row.data.draws[0].status='承認済み';row.data.draws[0].approvedAt=new Date(Date.now()+9*3600000).toISOString().slice(0,10);
  await call({action:'save',requestId:'award',version:row.version,data:structuredClone(row.data)},admin);
  await call({action:'save',requestId:'award2',version:row.version,data:structuredClone(row.data)},admin);
  assert.equal(row.data.achievements.length,1);assert.equal(row.data.draws.filter(d=>d.hidden).length,1);
  // Proposals: legacy state, owner visibility, admin-only review, atomic adoption.
  assert.equal((await call({action:'suggest_mission',requestId:'blank',text:'  '},student)).status,400);
  assert.equal((await call({action:'suggest_mission',requestId:'long',text:'x'.repeat(501)},student)).status,400);
  assert.equal((await call({action:'suggest_mission',requestId:'proposal',text:'英単語を覚える'},student)).status,200);
  await call({action:'suggest_mission',requestId:'proposal',text:'英単語を覚える'},student);
  assert.equal(row.data.missionSuggestions.length,1);
  const proposal=row.data.missionSuggestions[0];
  assert.equal((await call({action:'get'},other)).data.missionSuggestions.length,0);
  assert.equal((await call({action:'review_mission',requestId:'forbidden-review',id:proposal.id,decision:'accept'},student)).status,403);
  const oldClient=structuredClone(row.data);delete oldClient.missionSuggestions;
  await call({action:'save',requestId:'legacy-save',version:row.version,data:oldClient},admin);
  assert.equal(row.data.missionSuggestions.length,1);
  const count=row.data.missions.length;
  const stampsBefore=row.data.draws.filter(d=>d.studentId==='s1'&&d.status==='承認済み').reduce((n,d)=>n+(d.value||1),0);
  const accept={action:'review_mission',requestId:'accept-proposal',id:proposal.id,decision:'accept',text:'英単語を毎日10個覚える',deadlineDays:7,targetGroup:'juniorHigh'};
  assert.equal((await call({...accept,requestId:'bad-days',deadlineDays:0},admin)).status,400);
  assert.equal((await call(accept,admin)).status,200);
  await call(accept,admin);
  assert.equal(row.data.missions.length,count+1);
  assert.equal(row.data.missions.at(-1).targetGroup,'juniorHigh');
  assert.equal(row.data.missionSuggestions[0].status,'採用');
  const reward=row.data.draws.filter(d=>d.proposalReward);
  assert.equal(reward.length,1);assert.equal(reward[0].studentId,'s1');assert.equal(reward[0].value,1);
  assert.equal(reward[0].approvedAt,new Date(Date.now()+9*3600000).toISOString().slice(0,10));assert.equal(reward[0].hidden,true);
  assert.equal(row.data.draws.filter(d=>d.studentId==='s1'&&d.status==='承認済み').reduce((n,d)=>n+(d.value||1),0),stampsBefore+1);

  assert.equal((await call({...accept,requestId:'repeat-review'},admin)).status,409);
  await call({action:'suggest_mission',requestId:'proposal2',text:'別の案'},student);
  await call({action:'review_mission',requestId:'reject-proposal',id:row.data.missionSuggestions[1].id,decision:'reject'},admin);
  assert.equal(row.data.missionSuggestions[1].status,'見送り');
  assert.equal(row.data.missions.length,count+1);
  console.log('PASS: mission proposals, isolation, review authorization, validation, legacy preservation, adoption, duplicate protection, rejection');
  assert.equal(row.data.draws.filter(d=>d.proposalReward).length,1);
  const drawCount=row.data.draws.length;
  await call({action:'suggest',requestId:'prize-no-stamp',text:'景品案'},student);
  assert.equal(row.data.draws.length,drawCount);
  const prizeData=structuredClone(row.data);prizeData.prizeSuggestions.at(-1).status='採用(ランキング景品)';
  await call({action:'save',requestId:'prize-accept-no-stamp',version:row.version,data:prizeData},admin);
  assert.equal(row.data.draws.length,drawCount);
  console.log('PASS: one adoption stamp to proposer, idempotent retry, no rejection/prize suggestion/prize adoption stamps');
  row.data.milestonePrizes=[{id:'claimable',threshold:1,name:'文房具'},{id:'locked',threshold:9999,name:'未達成'}];
  const month=new Date(Date.now()+9*3600000).toISOString().slice(0,7);
  const claim={action:'claim_prize',requestId:'claim-one',month,type:'milestone',ref:'claimable'};
  assert.equal((await call({...claim,requestId:'claim-locked',ref:'locked'},student)).status,403);
  assert.equal((await call({...claim,requestId:'other-unearned'},other)).status,403);
  assert.equal((await call(claim,student)).status,200);
  assert.equal((await call({...claim,requestId:'claim-again'},student)).status,200);
  assert.equal(Object.keys(row.data.prizeClaims).length,1);
  const claimKey=Object.keys(row.data.prizeClaims)[0];
  assert.equal(row.data.prizeClaims[claimKey].studentId,'s1');
  assert.equal(Object.keys((await call({action:'get'},other)).data.prizeClaims).length,0);
  const legacySave=structuredClone(row.data);delete legacySave.prizeClaims;
  await call({action:'save',requestId:'legacy-claims-save',version:row.version,data:legacySave},admin);
  assert.equal(Object.keys(row.data.prizeClaims).length,1);
  row.data.milestonePrizes[0].name='変更後';
  assert.equal(row.data.prizeClaims[claimKey].label,'1個達成: 文房具');
  row.data.deliveries[claimKey]=true;
  assert.equal((await call({...claim,requestId:'claim-delivered'},student)).status,409);
  console.log('PASS: earned-only claims, ownership, deduplication, legacy preservation, snapshot and received status');
  // Japan midnight: settle before accepting edits/claims, without a scheduled client.
  let clock=Date.parse('2026-09-30T14:59:59Z');
  ctx.Date=class extends Date {constructor(...args){super(...(args.length?args:[clock]));}static now(){return clock;}};
  row.data.rankPrizeMonth='2026-09';row.data.rankPrizeHistory={};
  row.data.rankPrizes={'1':'月末の最終景品','2':'二位の景品','3':''};
  row.data.draws=[{id:'last-month',studentId:'s1',status:'承認済み',approvedAt:'2026-09-30',value:10}];
  const rankClaim={action:'claim_prize',month:'2026-09',type:'rank',ref:'1'};
  assert.equal((await call({...rankClaim,requestId:'rank-too-early'},student)).status,403);
  const oldMonthVersion=row.version,oldMonthData=structuredClone(row.data);
  clock=Date.parse('2026-09-30T15:00:00Z');
  assert.equal(vm.runInContext('todayStr()',ctx),'2026-10-01');
  assert.equal((await call({action:'save',requestId:'stale-month-edit',version:oldMonthVersion,data:oldMonthData},admin)).status,409);
  assert.equal(row.data.rankPrizeMonth,'2026-10');
  assert.deepEqual(row.data.rankPrizes,{'1':'','2':'','3':''});
  const archived=JSON.stringify(row.data.rankPrizeHistory['2026-09']);
  assert.equal(row.data.rankPrizeHistory['2026-09'].earned[0].label,'1位: 月末の最終景品');
  const edit=structuredClone(row.data);edit.rankPrizes['1']='翌月の別景品';delete edit.rankPrizeHistory;delete edit.rankPrizeMonth;
  assert.equal((await call({action:'save',requestId:'new-month-settings',version:row.version,data:edit},admin)).status,200);
  assert.equal(JSON.stringify(row.data.rankPrizeHistory['2026-09']),archived);
  // Subsequent corrections do not change finalized winners.
  row.data.draws[0].studentId='s2';
  assert.equal((await call({...rankClaim,requestId:'rank-wrong-student'},other)).status,403);
  assert.equal((await call({...rankClaim,requestId:'rank-finalized'},student)).status,200);
  assert.equal(row.data.prizeClaims['s1|2026-09|rank|1'].label,'1位: 月末の最終景品');
  assert.equal((await call({...rankClaim,requestId:'rank-repeat'},student)).status,200);
  assert.equal((await call({...rankClaim,month:'2026-10',requestId:'new-month-early'},student)).status,403);
  const stable=row.version;await call({action:'get'},student);assert.equal(row.version,stable);
  assert.equal(JSON.stringify(row.data.rankPrizeHistory['2026-09']),archived);
  ctx.sample=structuredClone(row.data);
  vm.runInContext("closeRankMonths(sample,'2027-02')",ctx);
  assert.equal(ctx.sample.rankPrizeMonth,'2027-02');
  assert.equal(ctx.sample.rankPrizeHistory['2026-10'].prizes['1'],'翌月の別景品');
  assert.equal(ctx.sample.rankPrizeHistory['2026-11'].earned.length,0);
  assert.ok(ctx.sample.rankPrizeHistory['2027-01']);
  assert.equal(JSON.stringify(ctx.sample.rankPrizeHistory['2026-09']),archived);
  assert.equal(ctx.sample.deliveries[claimKey],true);
  row.data.draws.push({id:'deadline-stamps',studentId:'s1',status:'承認済み',approvedAt:'2026-09-30',value:10});
  row.data.milestonePrizes.push({id:'deadline-ok',threshold:1,name:'期限内'},{id:'deadline-expired',threshold:1,name:'期限切れ'});
  clock=Date.parse('2026-10-10T14:59:59Z');
  const deadlineClaim={action:'claim_prize',month:'2026-09',type:'milestone',ref:'deadline-ok'};
  assert.equal((await call({...deadlineClaim,requestId:'deadline-last-second'},student)).status,200);
  clock=Date.parse('2026-10-10T15:00:00Z');
  assert.equal((await call({...deadlineClaim,ref:'deadline-expired',requestId:'expired-new-claim'},student)).status,403);
  assert.equal((await call({...deadlineClaim,requestId:'expired-already-claimed'},student)).status,200);
  assert.ok(row.data.prizeClaims['s1|2026-09|milestone|deadline-ok']);
  assert.equal(vm.runInContext("milestoneClaimOpen('2026-12','2027-01-10')",ctx),true);
  assert.equal(vm.runInContext("milestoneClaimOpen('2026-12','2027-01-11')",ctx),false);
  // Run the actual frontend selection logic: award month is distinct from display month.
  const html=fs.readFileSync(root+'/index.html','utf8');
  const start=html.indexOf('  const myEarnedThisMonth = useMemo(() => {');
  const selection=html.slice(start+html.slice(start).indexOf('{')+1,html.indexOf('\n  },[draws,students',start));
  ctx.currentStudentId='s1';ctx.studentMonth='2026-10';ctx.prizeClaims={};
  ctx.shiftMonth=(key,delta)=>{const [y,m]=key.split('-').map(Number);return new Date(Date.UTC(y,m-1+delta,1)).toISOString().slice(0,7);};
  ctx.earnedForMonth=month=>[{studentId:'s1',type:'milestone',ref:'x',label:'スタンプ'},...(month==='2026-09'?[{studentId:'s1',type:'rank',ref:'1',label:'九月最終景品'}]:[])];
  clock=Date.parse('2026-10-10T14:59:59Z');
  const select=()=>vm.runInContext('(function(){'+selection+'})()',ctx);
  assert.equal(select().filter(e=>e.month==='2026-09').length,2);
  assert.equal(select().find(e=>e.type==='rank').month,'2026-09');
  clock=Date.parse('2026-10-10T15:00:00Z');
  assert.equal(select().filter(e=>e.month==='2026-09'&&e.type==='milestone').length,0);
  assert.equal(select().filter(e=>e.type==='rank').length,1);
  ctx.prizeClaims={'s1|2026-09|milestone|x':{studentId:'s1',month:'2026-09',type:'milestone',ref:'x',label:'申請済み'}};
  assert.equal(select().filter(e=>e.label==='申請済み').length,1);
  ctx.studentMonth='2026-09';ctx.prizeClaims={};
  assert.equal(select().filter(e=>e.type==='rank').length,0);
  console.log('PASS: next-month ranking display, award-month keys, JST 10th deadline, 11th rejection/hiding, claimed history retained, December rollover');
  ctx.Date=Date;
  console.log('PASS: JST rollover, next-month-only claims, frozen final prizes/winners, stale save protection, legacy clients, idempotent closure, inactive months and year rollover');
  await call({action:'logout'},student);
  assert.equal((await call({action:'get'},student)).status,401);
  console.log('PASS: authentication, authorization, initial import, student isolation, request privacy/expiry, idempotency, draw limit, conflict protection, rewards, logout');
})().catch(e=>{console.error(e);process.exitCode=1;});
